version: '3.8'

services:
  php_fpm:
    build:
      context: .
      dockerfile: ./Dockerfile.php
      args:
        UID: 1002
        GID: 1005  
    container_name: php_cadjedi
    restart: unless-stopped
    expose:
      - "9000"  
    volumes:
      # 🔹 Voltamos ao volume normal (sem :cached) para evitar travamentos no WSL2
      - ./:/var/www/html 
    environment:
      # 🔹 Parâmetros de produção seguros que não travam o container
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
      - PHP_OPCACHE_MAX_ACCELERATED_FILES=20000
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0 # 0 força o PHP a ler da memória, sem checar o HD toda hora
    hostname: php_cadjedi
    networks:
      - my-shared-network

  nginx_cadjedi:
    image: nginx:alpine
    container_name: nginx_cadjedi
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html # 🔹 Volume normal aqui também
      - graficos_data:/var/www/html/mad/app/output/charts:ro
    ports:
      - "80:80"
    networks:
      - my-shared-network

volumes:
  graficos_data:
    external:
      name: python_service_graficos_data

networks:
  my-shared-network:
    external: true