host = "mariadb_db"
port = "3306"
name = "platia"
user = "root"
pass = "mys2Edu4Up@2025"
type = "mysql"
prep = "1"

;host = "jedieduca.mysql.dbaas.com.br"
;port = ""
;name = "jedieduca"
;user = "jedieduca"
;pass = "jediEduca@2025"
;type = "mysql"
;prep = "1"

//jedieduca.com.br Database hostinger
;host = "172.19.0.4"
;port = "3306"
;name = "jedieduca"
;user = "root"
;pass = "mys2Edu4Up@2025"
;type = "mysql"
;prep = "1"