[general]
timezone = America/Sao_Paulo
language = pt
application = cadJogos
title = "Módulo Backoffice do JEDi Educa"
theme = theme3
seed = 
rest_key = 
multiunit = "1"
debug = 0
multi_lang = "1"
lang_options[pt] = Português
lang_options[en] = English
lang_options[es] = Español
multi_database = "1"
base_url = "http://adm.dev.jedieduca.com.br"
;public_view = "1"
;public_entry = "PublicView"

;request_log_service = SystemRequestLogService
;request_log = 1
;request_log_types = cli,web,rest

[permission]
; Public classes, anyone (logged or not) has access
public_classes[] = PublicForm
public_classes[] = PublicView
public_classes[] = SystemRequestPasswordResetForm
public_classes[] = SystemPasswordResetForm
public_classes[] = SystemModulesCheckView
public_classes[] = SystemRegistrationForm

user_register    = "1"  ; users may auto register
reset_password   = "1"  ; users may reset password
default_groups   = "4"  ; default groups for auto registered users
default_screen   = "10" ; default screen for auto registered users
default_units    = "1"  ; default unit for auto registered users
;auth_service = LdapAuthenticationService

[openai]
apikey = "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"
model  = "gpt-4.1-mini"

[dir]
fotos = "fotos/"
