;host = "127.0.0.1"
;port = ""
;name = "jedieduca"
;;user = "root"
;pass = ""
;type = "mysql"
;prep = "1"

;host = "jedieduca.mysql.dbaas.com.br"
;port = ""
;name = "jedieduca"
;user = "jedieduca"
;pass = "jediEduca@2025"
;type = "mysql"
;prep = "1"

host = "mariadb_db"
port = "3306"
name = "jedieduca"
user = "root"
pass = "mys2Edu4Up@2025"
type = "mysql"
prep = "1"
