;host = "127.0.0.1"
;port = ""
;name = "jedi-permissions"
;user = "root"
;pass = ""
;type = "mysql"
;prep = "1"


//jedieduca.com.br Database hostinger
host = "172.19.0.6"
port = "3306"
name = "jedi-permissions"
user = "root"
pass = "mys2Edu4Up@2025"
type = "mysql"
prep = "1"