;host   = 
;port   = 
;name   = app/database/permission.db
;user   = 
;pass   = 
;type   = sqlite
;slog   = 
;prep   = "1"
;;slog   = SystemSqlLogService

host = "127.0.0.1"
port = ""
name = "permission"
user = "root"
pass = ""
type = "mysql"
prep = "1"

;host = "memopermission.mysql.dbaas.com.br"
;port = ""
;name = "memopermission"
;user = "memopermission"
;pass = "memore-net#21"
;type = "mysql"
;prep = "1"